### ISSUE TITLE
Check memory leak issue

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/jet-image-loader#14]
Here http://stackoverflow.com/questions/17261114/image-source-and-caching/19339901#19339901 in comments

**Comment by ghost** [comment]
Thanks for paying attention to my request. 
I'll take a look on the leak on this weekend, but first i'm trying to build your loader for wp7.

**Comment by artem-zinnatullin** [comment]
`JetImageLoader` using some features of C# that would not work in WP7, like `async/await`, so you can't build it for WP7.

But I think, as WP7 is not supported by Microsoft, we should concentrate working on WP8 version and port it to Windows 8 Store applications framework

**Comment by ghost** [comment]
I'm using Microsoft.Bcl for async/await in wp7, so far it worked good.
However, now i'm facing lots of errors like "Cannot await 'System.Threading.Tasks.Task<System.IO.Stream>'". 
To said honestly, now i have no idea, if it is possible to solve it.

I'd like to forget wp7, but about a half of users are still on it :(

**Comment by artem-zinnatullin** [comment]
You should forget wp7, or you will spend too much time to providing support for it, sad but true.

Android developers faced same problem with supporting API < 14 (android 4.0) and most of top developers decided to provide support only for API >= 14 when creating new apps. Article: [Why it's time to support only android 4.0 and above](http://dannyroa.com/2013/10/17/why-its-time-to-support-only-android-4-0-and-above/?utm_source=Android+Weekly&utm_campaign=2293b002e6-Android_Weekly_75&utm_medium=email&utm_term=0_4eb677ad19-2293b002e6-337297969)

**Comment by ghost** [comment]
Lol. I definitely should go and sell some hamburgers xD
I added wrong Nuget package... now it compiles fine.

Actually, having Microsoft.Bcl.Async (correct name, https://www.nuget.org/packages/Microsoft.Bcl.Async) provides wp7 with async/await. There's no reason to forbid wp7 as i still didnt meet anything critical for wp8 only.
There's full compatibility wp7 -> wp8, so its okay for me to develop wp7 app and share it to wp7+wp8 market.

Anyway, i didnt change your code, just added _correct_ nuget package, and that's it. I'll do some more tests to confirm that your lib works with wp7 and will proceed to leak testing mentioned above.

**Comment by ghost** [comment]
Damned, accidentally deleted post. Anyway, wp7 is used by 45% of users.

**Comment by artem-zinnatullin** [comment]
Great :) 

And great great great that it just works with `Microsoft.Bcl.Async`! You can update `README.md` for the project and add info about using `JetImageLoader` with `Microsoft.Bcl.Async`, I'll accept your pull request, or I can do this myself little later

May be you are right with your opinion about supporting wp7, but I am so fu***\* tired with supporting Android < 4.0 so I decided to stop it and focus on users with Android >= 4.0, same opinion about wp7 ;)

**Comment by ghost** [comment]
I think, its a bit early to abandon wp7 at the moment. Maybe next year or two. :)

I'll update Readme with all necessary info and pull project file after i'll check if my sample works. Have some strange exceptions in the project, would go deeper now.

**Comment by artem-zinnatullin** [comment]
ok, thank you very much!

**Comment by ghost** [comment]
Btw, which software are you using for editing *.md in Windows?

**Comment by artem-zinnatullin** [comment]
For editing `README.md` I use GitHub's online editing because I can click on "preview" and see how it would look here :)

Or you can use your favorite editor, you can read about GitHub's markdown here [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by ghost** [comment]
Hm.. i didnt work with github before.. is my fork there?

**Comment by artem-zinnatullin** [comment]
Yep, your fork is on GitHub [here](https://github.com/VeTaLNearga/jet-image-loader) you can make changes and then send pull request to initial repository, I'll check it and do merge

**Comment by ghost** [comment]
Ah, just made a pull request.

**Comment by artem-zinnatullin** [comment]
Can we close this issue?

**Comment by Nearga** [comment]
Not yet. I still should do a crash-test on Lumia 800.

**Comment by adrianhescalante** [comment]
Any news about the WP7 memory leaks? Can I use this library with WP7?

**Comment by artem-zinnatullin** [comment]
Yep, @Neagara did a test with Microsoft BCL library (for async/await support on wp7) on wp7, he had scrolled list with over 2000 items with images and did not get any OutOfMemory error.

So, I think you can use JetImageLoader without warning about memory leaks :) 

Happy new year by the way :)

**Comment by adrianhescalante** [comment]
Thanks! Good work here with this library.

Happy new year to you too :D
