### ISSUE TITLE
Its not working for Windows 10 universal app development.Is there any alternative?

### ISSUE THREAD

**Issue by ghost** [artem-zinnatullin/jet-image-loader#38]
This is error message :
Reference to Type IsolatedStorageFile claims that it it defined in 'microlib' but it could not be found.

**Comment by daniel-luberda** [comment]
You could use this: https://github.com/molinch/FFImageLoading  

Sample project: https://github.com/molinch/FFImageLoading/blob/master/samples/Simple.WinPhone.Sample/MainPage.xaml

**Comment by artem-zinnatullin** [comment]
Feel free to fork JetImageLoader and add support for Windows 10 Universal Apps! I don't work with Windows for about 2 years now…
