### ISSUE TITLE
Jet-Image Loader is not working with my Aync Methods

### ISSUE THREAD

**Issue by its-veejay** [artem-zinnatullin/jet-image-loader#7]
Hi,

I tried to use Jet-Image Loader on my windows 8 phone application and it works fine over forms but once i try to apply the Jet-Image caching technique over the aync methods which bind information on async mode it won't work, below is the code which i am using: 
# XAML:

<ctl:LongListSelector x:Name="ListCards" VerticalAlignment="Center"
                    LayoutMode="Grid"  ItemsSource="{Binding greetingsList}"
                    SelectionChanged="lstCards_SelectionChanged"
                    GridCellSize="210,170">
                        ctl:LongListSelector.ItemTemplate
                            <DataTemplate>
                                <StackPanel Width="200" Height="170" VerticalAlignment="Center">  
                                        <Image Source="{Binding ImgPath, Converter={StaticResource SampleJetImageLoaderConverter}}"
                                               Width="180" Height="140"                                                
                                               HorizontalAlignment="Center"
                                               Stretch="UniformToFill" />

```
                            </StackPanel>
                        </DataTemplate>
                    </ctl:LongListSelector.ItemTemplate>
                </ctl:LongListSelector>
```
# Code:

 public class GetGreetingSchema {

```
        public Uri ImgPath
       {
          get { return _ImgPath; }
          set
           {
            SetProperty(ref _ImgPath, value);
           }
       }      
      }

public ObservableCollection<GetGreetingSchema> greetingsList { get; private set; }
    public card_List3()
    {
        InitializeComponent();
        greetingsList = new ObservableCollection<GetGreetingSchema>();
        DataContext = this;
    }

    protected override async void OnNavigatedTo(NavigationEventArgs e)
    {
        base.OnNavigatedTo(e);           
        try
        {
            await LoadDataAsync();             
        }
        catch (Exception listbindException)
        {
            ReusableMethods.LogStackTrace(listbindException);             
        }
    }

    private async Task LoadDataAsync()
    {
        var dataSource = new Container().Resolve<IfellowsCollection>();           
        greetingsList = await dataSource.BindGreetingsList(CatId, Contenttype);
        ListCards.ItemsSource = greetingsList;
    }
```

Please let me know if there is some solution with this approach which i am following

**Comment by artem-zinnatullin** [comment]
Hi, I think the problem is that your list item model has `Uri` typed property `ImgPath` with the image link, but `BaseImageLoaderConverter` can work only with `string` typed links, try to change type of `ImgPath` property to `string` from `Uri` and reply me if it helps :)

I will add ability to work with `Uri` typed links for `BaseImageLoaderConverter` in next release, thank you with that suggestion.

P.S. please edit your issue's markdown, at the moment, XAML and code blocks  are displaying incorrectly.

**Comment by artem-zinnatullin** [comment]
Referencing #8

**Comment by artem-zinnatullin** [comment]
v0.8.3 now has support of `Uri` typed values for `BaseJetImageLoaderConverter`, just update library via NuGet and check how it works with your problem

**Comment by its-veejay** [comment]
Now it's working like a charm, thanks Artem.

One more point i want to be get cleared before applying Jet-Image over my App, Is Jet-Image Loader replaces the old cached image if server end changes new image which is get cached over the app..

**Comment by artem-zinnatullin** [comment]
If you are using LimitedStorageCache implementation for storage cache it will delete old files to keep cache size in your limits, so old images will be replaced with new ones.

With JetImageLoader v0.8.3 if your app always displays small number of images with constant URIs, JetImageLoader won't reload them.

I am planing to add support for HEAD requests in v1.0 to check was image changed on server or not without downloading it, and then JetImageLoader will be able to reload image when it was changed on server.

On this week I will add maximum storage cache lifetime, so you will be able to set for example one week cache lifetime period and JetImageLoader will reload it anyway.

Stay tuned, watch JetImageLoader or star it, I'll notify you about that issue :)

**Comment by its-veejay** [comment]
Maximum storage cache lifetime will be the good solution for cleaning the old images :+1: I will wait for the next JetImageLoader Nuget Update..

**Comment by artem-zinnatullin** [comment]
@bijendrayadav now `JetImageLoader` supports `CacheMaxLifetimeInMillis` for Storage cache, I will prepare new release today you will need to just update `JetImageLoader`, default cache max lifetime for LimitedStorageCacheImpl is one week.
